# Generated by Django 5.2.5 on 2025-11-25 04:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=255)),
                ('qty', models.FloatField()),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('L', 'Litre'), ('ml', 'Millilitre'), ('pieces', 'Pieces')], max_length=30)),
                ('category', models.CharField(choices=[('Veggies', 'Veggies'), ('Dairy', 'Dairy'), ('Meat', 'Meat'), ('Spices', 'Spices'), ('Others', 'Others')], max_length=50)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('nutrition_info', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=20)),
                ('serving_size', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_meals', to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.ManyToManyField(related_name='used_in_meals', to='meal_plan.pantryitem')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('goal', models.CharField(blank=True, choices=[('Weight Loss', 'Weight Loss'), ('Weight Gain', 'Weight Gain'), ('Maintenance', 'Maintenance')], max_length=20)),
                ('dietary_pref', models.CharField(blank=True, choices=[('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Keto', 'Keto'), ('Paleo', 'Paleo'), ('Gluten-Free', 'Gluten-Free'), ('Dairy-Free', 'Dairy-Free'), ('Pescatarian', 'Pescatarian'), ('Low-Carb', 'Low-Carb'), ('Low-Fat', 'Low-Fat'), ('Nut-Free', 'Nut-Free'), ('Soy-Free', 'Soy-Free'), ('Halal', 'Halal'), ('Kosher', 'Kosher'), ('None', 'None')], max_length=30)),
                ('allergy_info', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, max_length=2000, null=True)),
                ('ingredients', models.JSONField(blank=True, default=dict)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], default='Lunch', max_length=20)),
                ('nutrition_info', models.JSONField(blank=True, null=True)),
                ('main_nutrients', models.JSONField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='meal_plan.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_plans', to='meal_plan.recipe')),
                ('dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinner_plans', to='meal_plan.recipe')),
                ('lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_plans', to='meal_plan.recipe')),
            ],
        ),
    ]
