# Generated by Django 5.2.5 on 2025-11-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('L', 'Litre'), ('ml', 'Millilitre')], max_length=30),
        ),
    ]
