# Generated by Django 5.2.5 on 2025-11-26 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedMeal',
        ),
    ]
