# Generated by Django 5.2.5 on 2025-11-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0004_delete_generatedmeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
